// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Dotenv = require("../src/dotenv.bs.js");
var Process = require("process");

Dotenv.config(/* None */0, /* () */0);

console.log(Process.env);

/*  Not a pure module */
