// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Dotenv = require("../src/dotenv.bs.js");
var Process = require("process");

var config = /* record */[
  /* path : Some */[".env.production"],
  /* encoding : None */0
];

Dotenv.config(/* Some */[config], /* () */0);

console.log(Process.env);

exports.config = config;
/*  Not a pure module */
