// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var Dotenv = require("../src/dotenv.bs.js");
var Process = require("process");

describe("BuckleScript Dotenv", (function () {
        return Jest.test("it should get dotenv config from custom path", (function () {
                      Dotenv.config(/* Some */[/* record */[
                              /* path : Some */["./__tests__/.env"],
                              /* encoding : None */0
                            ]], /* () */0);
                      var nodeEnv = Process.env;
                      var basicValue = nodeEnv["BASIC"];
                      return Jest.Expect[/* toEqual */12](/* Some */["basic"], Jest.Expect[/* expect */0](basicValue === undefined ? /* None */0 : [basicValue]));
                    }));
      }));

/*  Not a pure module */
